services:
    db-mysql:
        image: mysql:8.0.33
        container_name: mysql-automationyt
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-automationyt}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-1234567}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - 3383:3306
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - dev-automationyt
    web:
        depends_on:
            - db-mysql
        image: automationyt
        container_name: server-automationyt
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWUSER: ${WWWUSER:-1000}
                WWWGROUP: ${WWWGROUP:-1000}
        restart: always
        ports:
            - "8007:80"
        working_dir: /var/www/html/automationyt
        volumes:
            - .:/var/www/html/automationyt
            - storage-automationyt:/storage:rw
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - dev-automationyt
            - redeautomationyt
        cap_add:
            - NET_ADMIN
        links:
            - db-mysql
    
    redis:
        image: redis:latest
        container_name: redis-automationyt
        restart: always
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 3s
            timeout: 2s
            retries: 3
        networks:
            - dev-automationyt

networks:
    dev-automationyt:
        driver: bridge
    redeautomationyt:
        external: true

volumes:
    mysql_data:
        driver: local
    storage-automationyt:
        external: true
        name: storage-automationyt