services:
    db-mysql:
        image: mysql:8.0.33
        container_name: mysql-wuapi
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-wuapi}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-1234567}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - 3383:3306
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - dev-wuapi
    web:
        depends_on:
            - db-mysql
        image: wuapi
        container_name: server-wuapi
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWUSER: ${WWWUSER:-1000}
                WWWGROUP: ${WWWGROUP:-1000}
        restart: always
        ports:
            - "8001:80"
        working_dir: /var/www/html/wuapi
        volumes:
            - .:/var/www/html/wuapi
            - storage-wuapi:/storage:rw
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - dev-wuapi
            - redewuapi
        cap_add:
            - NET_ADMIN
        links:
            - db-mysql
    
    redis:
        image: redis:latest
        container_name: redis-wuapi
        restart: always
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 3s
            timeout: 2s
            retries: 3
        networks:
            - dev-wuapi

networks:
    dev-wuapi:
        driver: bridge
    redewuapi:
        external: true

volumes:
    mysql_data:
        driver: local
    storage-wuapi:
        external: true
        name: storage-wuapi