#!/usr/bin/env bash

## Variáveis
source .env

# Iniciar o servidor WebSocket
# npm install && npm start

## Define usuário e Permissões dos arquivos
chown $WWWUSER:www-data -R /var/www/html/wuapi

chmod 775 -R /var/www/html/wuapi

### Instala os pacotes do composer
composer install --no-interaction --no-dev

### Otimização da aplicação
php artisan clear-compiled && php artisan optimize:clear

## GIT
git config --system --add safe.directory /var/www/html/wuapi
git config --system user.name "$GITNAME"
git config --system user.email "$GITEMAIL"

exec /usr/sbin/apache2ctl -D FOREGROUND

mkdir /.local
cd /.local/
chmod -R 777 ./

mkdir /storage
cd /storage/
chmod -R 777 ./

## Inicia o crontab
/bin/php /var/www/html/wuapi/artisan schedule:work >> /dev/null 2>&1